eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8050

spring:
  application:
    name: emprunts
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/emprunt_db
    username: postgres
    password: hadil123
  flyway:
    url: jdbc:postgresql://localhost:5432/emprunt_db
    user: postgres
    password: hadil123
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: stock
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'

