eureka:
  client:
    register-with-eureka: false

server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/emprunteurs/**
        - id: emprunts
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/emprunts/**
        - id: livres
          uri: http://localhost:8010
          predicates:
            - Path=/api/v1/livres/**

  application:
    name: gateway
