eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8010

spring:
  application:
    name: livres
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/livre_db
    username: postgres
    password: hhhh
  flyway:
    url: jdbc:postgresql://localhost:5432/livre_db
    user: postgres
    password: hhhh


